# Dev Container overrides for compose.yaml
services:
  dev:
    # Keep container running for VS Code to attach
    command: /bin/sh -c "while sleep 1000; do :; done"
    init: true
    stop_grace_period: 1s
